### PR TITLE
feat: add allow_destroy_plan and auto_apply flags for workspaces

### PR DESCRIPTION
**Pull request by jpetrucciani**
This PR just adds a couple more options, defaulting to their current state in the module!

### CODE REVIEW

**Review by mbevc1 — DISMISSED** [review]
Thanks for your contribution :+1:

**Comment by mbevc1** [comment]
Would you mind pushing an empty request to trigger checkes please?

**Review by mbevc1 — APPROVED** [review]

**Comment by mbevc1** [comment]
huh, need to check branch protections why this is not starting here...

**Comment by mbevc1** [comment]
Seems like it was filtering only on this repo branches. Could you please try rebasing and pushing please?

**Comment by jpetrucciani** [comment]
sure, just a min!

**Comment by jpetrucciani** [comment]
@mbevc1 should be good to run workflows on now! rebased off of latest from main - should be just the new commit there now

**Review by mbevc1 — APPROVED** [review]

**Comment by mbevc1** [comment]
Perfect, thanks again! Looks good now :+1:

**Pull request merged**
